### ISSUE TITLE
Error running examples

### ISSUE THREAD

**Issue by carlosarmentac** [jalmeroth/homie-python#33]
I try to run an example temperature_sensor.py in a raspberry py and in a Desktop PC with Ubuntu 16.04 with the same result.

>>> Homie.setup()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/homie/main.py", line 211, in setup
    self._initialize()
  File "/usr/local/lib/python2.7/dist-packages/homie/main.py", line 147, in _initialize
    self.mqtt.connect(self.host, self.port, self.keepalive)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 760, in connect
    return self.reconnect()
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 932, in reconnect
    return self._send_connect(self._keepalive, self._clean_session)
  File "/usr/local/lib/python2.7/dist-packages/paho/mqtt/client.py", line 2114, in _send_connect
    keepalive))
struct.error: cannot convert argument to integer

**Comment by jalmeroth** [comment]
I pushed a new version 0.2.2 that should fix the issue. 
Could you please update your version, test and give me feedback?
